import { CSSProperties } from "react";

export const entranceStyles: { [key: string]: CSSProperties } = {
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    backgroundColor: "#E74C3C",
    textAlign: "center",
    fontFamily: "'Arial', sans-serif",
  },
  errorMessage: {
    fontSize: "3rem",
    color: "#ffffff",
    textShadow: "2px 2px 6px rgba(0, 0, 0, 0.3)",
  },
  successContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    backgroundColor: "#2ECC71",
    textAlign: "center",
    fontFamily: "'Arial', sans-serif",
  },
  plateBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    border: "3px solid #000000",
    borderRadius: "8px",
    padding: "10px 30px",
    boxShadow: "0 6px 12px rgba(0, 0, 0, 0.1)",
    marginBottom: "20px",
    width: "300px",
    height: "100px",
    position: "relative",
  },
  euroBand: {
    position: "absolute",
    left: "0",
    height: "100%",
    width: "50px",
    backgroundColor: "#003399",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    fontWeight: "bold",
    borderRadius: "4px 0 0 4px",
  },
  euroStars: {
    position: "relative",
    width: "30px",
    height: "30px",
    display: "inline-block",
    marginBottom: "25px",
  },
  star: {
    position: "absolute",
    width: "3px",
    height: "3px",
    backgroundColor: "yellow",
    borderRadius: "50%",
  },
  star1: { top: "0%", left: "50%" },
  star2: { top: "15%", left: "85%" },
  star3: { top: "50%", left: "100%" },
  star4: { top: "85%", left: "85%" },
  star5: { top: "100%", left: "50%" },
  star6: { top: "85%", left: "15%" },
  star7: { top: "50%", left: "0%" },
  star8: { top: "15%", left: "15%" },
  plateText: {
    fontSize: "3rem",
    color: "#000000",
    fontWeight: "bold",
    letterSpacing: "5px",
    marginLeft: "60px",
  },
  countryCode: {
    marginTop: "30px",
  },
  infoText: {
    fontSize: "5rem",
    color: "#ffffff",
    textShadow: "1px 1px 4px rgba(0, 0, 0, 0.3)",
  },
};
